  version: '3.8'
  services:
    db:
      image: mysql:8
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: todo
      ports:
        - "3306:3306"
      volumes:
        - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

    backend:
      build: ./backend
      environment:
        DB_HOST: db
        DB_USER: root
        DB_PASSWORD: root
        DB_NAME: todo
      ports:
        - "5000:5000"
      depends_on:
        - db

    frontend:
      build: ./frontend/frontend
      ports:
        - "3000:3000"
      depends_on:
        - backend

  volumes:
    db_data: